spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/news_forum?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum

    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB
#  spring.servlet.multipart.enabled=true
#  spring.servlet.multipart.file-size-threshold=2KB
#  spring.servlet.multipart.max-file-size=200MB
#  spring.servlet.multipart.max-request-size=215MB
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
